// ⚠️  GENERATED FILE - DO NOT EDIT
// This file is automatically generated by 'prisma contract emit'.
// To regenerate, run: prisma contract emit
import type { QueryOperationTypes as PgAdapterQueryOps } from '@prisma/orm-postgres/adapter/operation-types';
import type {
  Bit,
  Char,
  CodecTypes as PgTypes,
  Interval,
  JsonValue,
  Numeric,
  Time,
  TimeString,
  Timestamp,
  TimestampString,
  Timestamptz,
  TimestamptzString,
  Timetz,
  VarBit,
  Varchar,
} from '@prisma/orm-postgres/target/codec-types';

import type {
  ContractWithTypeMaps,
  TypeMaps as TypeMapsType,
} from '@prisma/orm-postgres/family-contract/types';
import type {
  Contract as ContractType,
  ExecutionHashBase,
  NamespaceId,
  ProfileHashBase,
  StorageHashBase,
} from '@prisma/orm-postgres/contract/types';

export type StorageHash =
  StorageHashBase<'f87f92961b58681b3ba290810146629710236689323db6d982790bed93915fca'>;
export type ExecutionHash = ExecutionHashBase<string>;
export type ProfileHash =
  ProfileHashBase<'3916f444a8a17ad749191acf9e08dad97d1a327b88c2f1d45d12f240296aa8b2'>;

export type CodecTypes = PgTypes;
export type LaneCodecTypes = CodecTypes;
export type QueryOperationTypes = PgAdapterQueryOps<CodecTypes>;
export type AggregateTypes = {
  readonly avg: {
    readonly byCodec: {
      readonly 'pg/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
    };
  };
  readonly avgDecimal: {
    readonly byCodec: {
      readonly 'pg/int@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
    };
  };
  readonly count: {
    readonly byCodec: {};
    readonly withoutInput: { readonly output: 'pg/int8number@1'; readonly nullable: false };
    readonly anyInput: { readonly output: 'pg/int8number@1'; readonly nullable: false };
  };
  readonly countBigInt: {
    readonly byCodec: {};
    readonly withoutInput: { readonly output: 'pg/int8@1'; readonly nullable: false };
    readonly anyInput: { readonly output: 'pg/int8@1'; readonly nullable: false };
  };
  readonly max: {
    readonly byCodec: {
      readonly 'pg/char@1': { readonly output: 'pg/char@1'; readonly nullable: true };
      readonly 'pg/date-string@1': { readonly output: 'pg/date-string@1'; readonly nullable: true };
      readonly 'pg/date-temporal@1': {
        readonly output: 'pg/date-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/enum@1': { readonly output: 'pg/enum@1'; readonly nullable: true };
      readonly 'pg/float@1': { readonly output: 'pg/float@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/inet@1': { readonly output: 'pg/inet@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int2@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int4@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/text-array@1': { readonly output: 'pg/text-array@1'; readonly nullable: true };
      readonly 'pg/text@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/time-string@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': {
        readonly output: 'pg/time-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-string@1': {
        readonly output: 'pg/timestamp-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-temporal@1': {
        readonly output: 'pg/timestamp-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-string@1': {
        readonly output: 'pg/timestamptz-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-temporal@1': {
        readonly output: 'pg/timestamptz-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timetz@1': { readonly output: 'pg/timetz@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'pg/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'sql/char@1': { readonly output: 'sql/char@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'sql/float@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'sql/int@1'; readonly nullable: true };
      readonly 'sql/text@1': { readonly output: 'sql/text@1'; readonly nullable: true };
      readonly 'sql/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
    };
  };
  readonly min: {
    readonly byCodec: {
      readonly 'pg/char@1': { readonly output: 'pg/char@1'; readonly nullable: true };
      readonly 'pg/date-string@1': { readonly output: 'pg/date-string@1'; readonly nullable: true };
      readonly 'pg/date-temporal@1': {
        readonly output: 'pg/date-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/enum@1': { readonly output: 'pg/enum@1'; readonly nullable: true };
      readonly 'pg/float@1': { readonly output: 'pg/float@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/inet@1': { readonly output: 'pg/inet@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int2@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int4@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/text-array@1': { readonly output: 'pg/text-array@1'; readonly nullable: true };
      readonly 'pg/text@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/time-string@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': {
        readonly output: 'pg/time-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-string@1': {
        readonly output: 'pg/timestamp-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-temporal@1': {
        readonly output: 'pg/timestamp-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-string@1': {
        readonly output: 'pg/timestamptz-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-temporal@1': {
        readonly output: 'pg/timestamptz-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timetz@1': { readonly output: 'pg/timetz@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'pg/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'sql/char@1': { readonly output: 'sql/char@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'sql/float@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'sql/int@1'; readonly nullable: true };
      readonly 'sql/text@1': { readonly output: 'sql/text@1'; readonly nullable: true };
      readonly 'sql/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
    };
  };
  readonly sum: {
    readonly byCodec: {
      readonly 'pg/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'sql/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
    };
  };
  readonly sumBigInt: {
    readonly byCodec: {
      readonly 'pg/int@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/unboundedint@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/unboundedint@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'sql/int@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
    };
  };
};
type DefaultLiteralValue<CodecId extends string, Encoded> = CodecId extends keyof CodecTypes
  ? Encoded extends CodecTypes[CodecId]['json']
    ? Encoded
    : CodecTypes[CodecId]['json']
  : Encoded;

export type FieldOutputTypes = {
  readonly public: {
    readonly Area: {
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly name: CodecTypes['pg/text@1']['output'];
    };
    readonly Buyer: {
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly clientId: CodecTypes['pg/int4@1']['output'];
      readonly areaId: CodecTypes['pg/int4@1']['output'];
      readonly length: CodecTypes['pg/int4@1']['output'];
      readonly width: CodecTypes['pg/int4@1']['output'];
      readonly budget: CodecTypes['pg/int4@1']['output'];
      readonly status: 'NOTPURCHASED' | 'PURCHASED' | 'CANCELLED';
      readonly remarks: CodecTypes['pg/text@1']['output'] | null;
    };
    readonly Client: {
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly name: CodecTypes['pg/text@1']['output'];
      readonly address: CodecTypes['pg/text@1']['output'];
      readonly mobileNumber: CodecTypes['pg/text@1']['output'];
      readonly remarks: CodecTypes['pg/text@1']['output'] | null;
    };
    readonly Colony: {
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly name: CodecTypes['pg/text@1']['output'];
      readonly areaId: CodecTypes['pg/int4@1']['output'];
    };
    readonly Employee: {
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly name: CodecTypes['pg/text@1']['output'];
      readonly phoneNumber: CodecTypes['pg/text@1']['output'];
    };
    readonly Flat: {
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly floorId: CodecTypes['pg/int4@1']['output'];
      readonly type: CodecTypes['pg/text@1']['output'];
      readonly flatNumber: CodecTypes['pg/text@1']['output'];
      readonly status: 'AVAILABLE' | 'SOLD';
    };
    readonly Floor: {
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly wingId: CodecTypes['pg/int4@1']['output'];
      readonly numberOfFlats: CodecTypes['pg/int4@1']['output'];
    };
    readonly FollowUp: {
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly clientId: CodecTypes['pg/int4@1']['output'];
      readonly employeeId: CodecTypes['pg/int4@1']['output'];
      readonly dateTime: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly notes: CodecTypes['pg/text@1']['output'] | null;
      readonly status: 'PENDING' | 'DONE' | 'POSTPONED' | 'CANCELLED';
      readonly purpose: 'GENERAL' | 'MARKETING' | 'BUYER' | 'SELLER';
    };
    readonly Marketing: {
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly clientId: CodecTypes['pg/int4@1']['output'];
      readonly employeeId: CodecTypes['pg/int4@1']['output'] | null;
      readonly colonyId: CodecTypes['pg/int4@1']['output'];
      readonly remarks: CodecTypes['pg/text@1']['output'] | null;
      readonly status: 'NONE' | 'CALLED_NOT_VISITED' | 'VISITED' | 'NOT_INTERESTED';
      readonly priority: 'ONE_STAR' | 'TWO_STAR' | 'THREE_STAR' | 'FOUR_STAR' | 'FIVE_STAR';
    };
    readonly Seller: {
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly clientId: CodecTypes['pg/int4@1']['output'];
      readonly areaId: CodecTypes['pg/int4@1']['output'];
      readonly length: CodecTypes['pg/int4@1']['output'];
      readonly width: CodecTypes['pg/int4@1']['output'];
      readonly demand: CodecTypes['pg/int4@1']['output'];
      readonly status: 'UNSOLD' | 'SOLD';
      readonly remarks: CodecTypes['pg/text@1']['output'] | null;
    };
    readonly Wing: {
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly colonyId: CodecTypes['pg/int4@1']['output'];
      readonly name: CodecTypes['pg/text@1']['output'];
      readonly numberOfFloors: CodecTypes['pg/int4@1']['output'];
    };
  };
};
export type FieldInputTypes = {
  readonly public: {
    readonly Area: {
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly name: CodecTypes['pg/text@1']['input'];
    };
    readonly Buyer: {
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly clientId: CodecTypes['pg/int4@1']['input'];
      readonly areaId: CodecTypes['pg/int4@1']['input'];
      readonly length: CodecTypes['pg/int4@1']['input'];
      readonly width: CodecTypes['pg/int4@1']['input'];
      readonly budget: CodecTypes['pg/int4@1']['input'];
      readonly status: 'NOTPURCHASED' | 'PURCHASED' | 'CANCELLED';
      readonly remarks: CodecTypes['pg/text@1']['input'] | null;
    };
    readonly Client: {
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly name: CodecTypes['pg/text@1']['input'];
      readonly address: CodecTypes['pg/text@1']['input'];
      readonly mobileNumber: CodecTypes['pg/text@1']['input'];
      readonly remarks: CodecTypes['pg/text@1']['input'] | null;
    };
    readonly Colony: {
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly name: CodecTypes['pg/text@1']['input'];
      readonly areaId: CodecTypes['pg/int4@1']['input'];
    };
    readonly Employee: {
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly name: CodecTypes['pg/text@1']['input'];
      readonly phoneNumber: CodecTypes['pg/text@1']['input'];
    };
    readonly Flat: {
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly floorId: CodecTypes['pg/int4@1']['input'];
      readonly type: CodecTypes['pg/text@1']['input'];
      readonly flatNumber: CodecTypes['pg/text@1']['input'];
      readonly status: 'AVAILABLE' | 'SOLD';
    };
    readonly Floor: {
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly wingId: CodecTypes['pg/int4@1']['input'];
      readonly numberOfFlats: CodecTypes['pg/int4@1']['input'];
    };
    readonly FollowUp: {
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly clientId: CodecTypes['pg/int4@1']['input'];
      readonly employeeId: CodecTypes['pg/int4@1']['input'];
      readonly dateTime: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly notes: CodecTypes['pg/text@1']['input'] | null;
      readonly status: 'PENDING' | 'DONE' | 'POSTPONED' | 'CANCELLED';
      readonly purpose: 'GENERAL' | 'MARKETING' | 'BUYER' | 'SELLER';
    };
    readonly Marketing: {
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly clientId: CodecTypes['pg/int4@1']['input'];
      readonly employeeId: CodecTypes['pg/int4@1']['input'] | null;
      readonly colonyId: CodecTypes['pg/int4@1']['input'];
      readonly remarks: CodecTypes['pg/text@1']['input'] | null;
      readonly status: 'NONE' | 'CALLED_NOT_VISITED' | 'VISITED' | 'NOT_INTERESTED';
      readonly priority: 'ONE_STAR' | 'TWO_STAR' | 'THREE_STAR' | 'FOUR_STAR' | 'FIVE_STAR';
    };
    readonly Seller: {
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly clientId: CodecTypes['pg/int4@1']['input'];
      readonly areaId: CodecTypes['pg/int4@1']['input'];
      readonly length: CodecTypes['pg/int4@1']['input'];
      readonly width: CodecTypes['pg/int4@1']['input'];
      readonly demand: CodecTypes['pg/int4@1']['input'];
      readonly status: 'UNSOLD' | 'SOLD';
      readonly remarks: CodecTypes['pg/text@1']['input'] | null;
    };
    readonly Wing: {
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly colonyId: CodecTypes['pg/int4@1']['input'];
      readonly name: CodecTypes['pg/text@1']['input'];
      readonly numberOfFloors: CodecTypes['pg/int4@1']['input'];
    };
  };
};
export type StorageColumnTypes = {
  readonly public: {
    readonly area: {
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly name: CodecTypes['pg/text@1']['output'];
    };
    readonly buyer: {
      readonly areaId: CodecTypes['pg/int4@1']['output'];
      readonly budget: CodecTypes['pg/int4@1']['output'];
      readonly clientId: CodecTypes['pg/int4@1']['output'];
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly length: CodecTypes['pg/int4@1']['output'];
      readonly remarks: CodecTypes['pg/text@1']['output'] | null;
      readonly status: 'NOTPURCHASED' | 'PURCHASED' | 'CANCELLED';
      readonly width: CodecTypes['pg/int4@1']['output'];
    };
    readonly client: {
      readonly address: CodecTypes['pg/text@1']['output'];
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly mobileNumber: CodecTypes['pg/text@1']['output'];
      readonly name: CodecTypes['pg/text@1']['output'];
      readonly remarks: CodecTypes['pg/text@1']['output'] | null;
    };
    readonly colony: {
      readonly areaId: CodecTypes['pg/int4@1']['output'];
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly name: CodecTypes['pg/text@1']['output'];
    };
    readonly employee: {
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly name: CodecTypes['pg/text@1']['output'];
      readonly phoneNumber: CodecTypes['pg/text@1']['output'];
    };
    readonly flat: {
      readonly flatNumber: CodecTypes['pg/text@1']['output'];
      readonly floorId: CodecTypes['pg/int4@1']['output'];
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly status: 'AVAILABLE' | 'SOLD';
      readonly type: CodecTypes['pg/text@1']['output'];
    };
    readonly floor: {
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly numberOfFlats: CodecTypes['pg/int4@1']['output'];
      readonly wingId: CodecTypes['pg/int4@1']['output'];
    };
    readonly followUp: {
      readonly clientId: CodecTypes['pg/int4@1']['output'];
      readonly dateTime: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly employeeId: CodecTypes['pg/int4@1']['output'];
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly notes: CodecTypes['pg/text@1']['output'] | null;
      readonly purpose: 'GENERAL' | 'MARKETING' | 'BUYER' | 'SELLER';
      readonly status: 'PENDING' | 'DONE' | 'POSTPONED' | 'CANCELLED';
    };
    readonly marketing: {
      readonly clientId: CodecTypes['pg/int4@1']['output'];
      readonly colonyId: CodecTypes['pg/int4@1']['output'];
      readonly employeeId: CodecTypes['pg/int4@1']['output'] | null;
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly priority: 'ONE_STAR' | 'TWO_STAR' | 'THREE_STAR' | 'FOUR_STAR' | 'FIVE_STAR';
      readonly remarks: CodecTypes['pg/text@1']['output'] | null;
      readonly status: 'NONE' | 'CALLED_NOT_VISITED' | 'VISITED' | 'NOT_INTERESTED';
    };
    readonly seller: {
      readonly areaId: CodecTypes['pg/int4@1']['output'];
      readonly clientId: CodecTypes['pg/int4@1']['output'];
      readonly demand: CodecTypes['pg/int4@1']['output'];
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly length: CodecTypes['pg/int4@1']['output'];
      readonly remarks: CodecTypes['pg/text@1']['output'] | null;
      readonly status: 'UNSOLD' | 'SOLD';
      readonly width: CodecTypes['pg/int4@1']['output'];
    };
    readonly wing: {
      readonly colonyId: CodecTypes['pg/int4@1']['output'];
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly name: CodecTypes['pg/text@1']['output'];
      readonly numberOfFloors: CodecTypes['pg/int4@1']['output'];
    };
  };
};
export type StorageColumnInputTypes = {
  readonly public: {
    readonly area: {
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly name: CodecTypes['pg/text@1']['input'];
    };
    readonly buyer: {
      readonly areaId: CodecTypes['pg/int4@1']['input'];
      readonly budget: CodecTypes['pg/int4@1']['input'];
      readonly clientId: CodecTypes['pg/int4@1']['input'];
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly length: CodecTypes['pg/int4@1']['input'];
      readonly remarks: CodecTypes['pg/text@1']['input'] | null;
      readonly status: 'NOTPURCHASED' | 'PURCHASED' | 'CANCELLED';
      readonly width: CodecTypes['pg/int4@1']['input'];
    };
    readonly client: {
      readonly address: CodecTypes['pg/text@1']['input'];
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly mobileNumber: CodecTypes['pg/text@1']['input'];
      readonly name: CodecTypes['pg/text@1']['input'];
      readonly remarks: CodecTypes['pg/text@1']['input'] | null;
    };
    readonly colony: {
      readonly areaId: CodecTypes['pg/int4@1']['input'];
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly name: CodecTypes['pg/text@1']['input'];
    };
    readonly employee: {
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly name: CodecTypes['pg/text@1']['input'];
      readonly phoneNumber: CodecTypes['pg/text@1']['input'];
    };
    readonly flat: {
      readonly flatNumber: CodecTypes['pg/text@1']['input'];
      readonly floorId: CodecTypes['pg/int4@1']['input'];
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly status: 'AVAILABLE' | 'SOLD';
      readonly type: CodecTypes['pg/text@1']['input'];
    };
    readonly floor: {
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly numberOfFlats: CodecTypes['pg/int4@1']['input'];
      readonly wingId: CodecTypes['pg/int4@1']['input'];
    };
    readonly followUp: {
      readonly clientId: CodecTypes['pg/int4@1']['input'];
      readonly dateTime: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly employeeId: CodecTypes['pg/int4@1']['input'];
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly notes: CodecTypes['pg/text@1']['input'] | null;
      readonly purpose: 'GENERAL' | 'MARKETING' | 'BUYER' | 'SELLER';
      readonly status: 'PENDING' | 'DONE' | 'POSTPONED' | 'CANCELLED';
    };
    readonly marketing: {
      readonly clientId: CodecTypes['pg/int4@1']['input'];
      readonly colonyId: CodecTypes['pg/int4@1']['input'];
      readonly employeeId: CodecTypes['pg/int4@1']['input'] | null;
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly priority: 'ONE_STAR' | 'TWO_STAR' | 'THREE_STAR' | 'FOUR_STAR' | 'FIVE_STAR';
      readonly remarks: CodecTypes['pg/text@1']['input'] | null;
      readonly status: 'NONE' | 'CALLED_NOT_VISITED' | 'VISITED' | 'NOT_INTERESTED';
    };
    readonly seller: {
      readonly areaId: CodecTypes['pg/int4@1']['input'];
      readonly clientId: CodecTypes['pg/int4@1']['input'];
      readonly demand: CodecTypes['pg/int4@1']['input'];
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly length: CodecTypes['pg/int4@1']['input'];
      readonly remarks: CodecTypes['pg/text@1']['input'] | null;
      readonly status: 'UNSOLD' | 'SOLD';
      readonly width: CodecTypes['pg/int4@1']['input'];
    };
    readonly wing: {
      readonly colonyId: CodecTypes['pg/int4@1']['input'];
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly name: CodecTypes['pg/text@1']['input'];
      readonly numberOfFloors: CodecTypes['pg/int4@1']['input'];
    };
  };
};
export type TypeMaps = TypeMapsType<
  CodecTypes,
  QueryOperationTypes,
  FieldOutputTypes,
  FieldInputTypes,
  StorageColumnTypes,
  StorageColumnInputTypes,
  AggregateTypes
>;

type ContractBase = Omit<
  ContractType<{
    readonly namespaces: {
      readonly public: {
        readonly id: 'public';
        readonly kind: 'postgres-schema';
        readonly entries: {
          readonly table: {
            readonly area: {
              columns: {
                readonly id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                };
                readonly name: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
            readonly buyer: {
              columns: {
                readonly id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                };
                readonly clientId: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly areaId: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly length: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly width: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly budget: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly status: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/text@1', 'NOTPURCHASED'>;
                  };
                };
                readonly remarks: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'buyer_clientId_idx_153a9a49';
                  readonly prefix: 'buyer_clientId_idx';
                  readonly columns: readonly ['clientId'];
                  readonly unique: false;
                },
                {
                  readonly name: 'buyer_areaId_idx_abf7188c';
                  readonly prefix: 'buyer_areaId_idx';
                  readonly columns: readonly ['areaId'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'buyer';
                    readonly columns: readonly ['clientId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'client';
                    readonly columns: readonly ['id'];
                  };
                },
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'buyer';
                    readonly columns: readonly ['areaId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'area';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly client: {
              columns: {
                readonly id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                };
                readonly name: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly address: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly mobileNumber: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly remarks: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
            readonly colony: {
              columns: {
                readonly id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                };
                readonly name: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly areaId: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'colony_areaId_idx_abf7188c';
                  readonly prefix: 'colony_areaId_idx';
                  readonly columns: readonly ['areaId'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'colony';
                    readonly columns: readonly ['areaId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'area';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly employee: {
              columns: {
                readonly id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                };
                readonly name: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly phoneNumber: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
            readonly flat: {
              columns: {
                readonly id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                };
                readonly floorId: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly type: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly flatNumber: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly status: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/text@1', 'AVAILABLE'>;
                  };
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'flat_floorId_idx_f24b0a84';
                  readonly prefix: 'flat_floorId_idx';
                  readonly columns: readonly ['floorId'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'flat';
                    readonly columns: readonly ['floorId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'floor';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly floor: {
              columns: {
                readonly id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                };
                readonly wingId: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly numberOfFlats: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'floor_wingId_idx_68467838';
                  readonly prefix: 'floor_wingId_idx';
                  readonly columns: readonly ['wingId'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'floor';
                    readonly columns: readonly ['wingId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'wing';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly followUp: {
              columns: {
                readonly id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                };
                readonly clientId: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly employeeId: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly dateTime: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                };
                readonly notes: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly status: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/text@1', 'PENDING'>;
                  };
                };
                readonly purpose: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/text@1', 'GENERAL'>;
                  };
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'followUp_clientId_idx_153a9a49';
                  readonly prefix: 'followUp_clientId_idx';
                  readonly columns: readonly ['clientId'];
                  readonly unique: false;
                },
                {
                  readonly name: 'followUp_employeeId_idx_087dd4a6';
                  readonly prefix: 'followUp_employeeId_idx';
                  readonly columns: readonly ['employeeId'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'followUp';
                    readonly columns: readonly ['clientId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'client';
                    readonly columns: readonly ['id'];
                  };
                },
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'followUp';
                    readonly columns: readonly ['employeeId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'employee';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly marketing: {
              columns: {
                readonly id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                };
                readonly clientId: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly employeeId: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: true;
                };
                readonly colonyId: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly remarks: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly status: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/text@1', 'NONE'>;
                  };
                };
                readonly priority: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/text@1', 'ONE_STAR'>;
                  };
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'marketing_clientId_idx_153a9a49';
                  readonly prefix: 'marketing_clientId_idx';
                  readonly columns: readonly ['clientId'];
                  readonly unique: false;
                },
                {
                  readonly name: 'marketing_employeeId_idx_087dd4a6';
                  readonly prefix: 'marketing_employeeId_idx';
                  readonly columns: readonly ['employeeId'];
                  readonly unique: false;
                },
                {
                  readonly name: 'marketing_colonyId_idx_fe680993';
                  readonly prefix: 'marketing_colonyId_idx';
                  readonly columns: readonly ['colonyId'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'marketing';
                    readonly columns: readonly ['clientId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'client';
                    readonly columns: readonly ['id'];
                  };
                },
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'marketing';
                    readonly columns: readonly ['employeeId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'employee';
                    readonly columns: readonly ['id'];
                  };
                },
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'marketing';
                    readonly columns: readonly ['colonyId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'colony';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly seller: {
              columns: {
                readonly id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                };
                readonly clientId: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly areaId: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly length: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly width: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly demand: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly status: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/text@1', 'UNSOLD'>;
                  };
                };
                readonly remarks: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'seller_clientId_idx_153a9a49';
                  readonly prefix: 'seller_clientId_idx';
                  readonly columns: readonly ['clientId'];
                  readonly unique: false;
                },
                {
                  readonly name: 'seller_areaId_idx_abf7188c';
                  readonly prefix: 'seller_areaId_idx';
                  readonly columns: readonly ['areaId'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'seller';
                    readonly columns: readonly ['clientId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'client';
                    readonly columns: readonly ['id'];
                  };
                },
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'seller';
                    readonly columns: readonly ['areaId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'area';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly wing: {
              columns: {
                readonly id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                };
                readonly colonyId: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly name: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly numberOfFloors: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'wing_colonyId_idx_fe680993';
                  readonly prefix: 'wing_colonyId_idx';
                  readonly columns: readonly ['colonyId'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'wing';
                    readonly columns: readonly ['colonyId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'colony';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
          };
          readonly valueSet: {
            readonly BuyerStatus: {
              readonly kind: 'valueSet';
              readonly values: readonly ['NOTPURCHASED', 'PURCHASED', 'CANCELLED'];
            };
            readonly FlatStatus: {
              readonly kind: 'valueSet';
              readonly values: readonly ['AVAILABLE', 'SOLD'];
            };
            readonly FollowUpPurpose: {
              readonly kind: 'valueSet';
              readonly values: readonly ['GENERAL', 'MARKETING', 'BUYER', 'SELLER'];
            };
            readonly FollowUpStatus: {
              readonly kind: 'valueSet';
              readonly values: readonly ['PENDING', 'DONE', 'POSTPONED', 'CANCELLED'];
            };
            readonly MarketingStatus: {
              readonly kind: 'valueSet';
              readonly values: readonly ['NONE', 'CALLED_NOT_VISITED', 'VISITED', 'NOT_INTERESTED'];
            };
            readonly Priority: {
              readonly kind: 'valueSet';
              readonly values: readonly [
                'ONE_STAR',
                'TWO_STAR',
                'THREE_STAR',
                'FOUR_STAR',
                'FIVE_STAR',
              ];
            };
            readonly SellerStatus: {
              readonly kind: 'valueSet';
              readonly values: readonly ['UNSOLD', 'SOLD'];
            };
          };
        };
      };
    };
    readonly storageHash: StorageHash;
  }>,
  'roots' | 'domain'
> & {
  readonly target: 'postgres';
  readonly targetFamily: 'sql';
  readonly roots: {
    readonly client: { readonly namespace: 'public' & NamespaceId; readonly model: 'Client' };
    readonly area: { readonly namespace: 'public' & NamespaceId; readonly model: 'Area' };
    readonly seller: { readonly namespace: 'public' & NamespaceId; readonly model: 'Seller' };
    readonly buyer: { readonly namespace: 'public' & NamespaceId; readonly model: 'Buyer' };
    readonly colony: { readonly namespace: 'public' & NamespaceId; readonly model: 'Colony' };
    readonly employee: { readonly namespace: 'public' & NamespaceId; readonly model: 'Employee' };
    readonly marketing: { readonly namespace: 'public' & NamespaceId; readonly model: 'Marketing' };
    readonly wing: { readonly namespace: 'public' & NamespaceId; readonly model: 'Wing' };
    readonly floor: { readonly namespace: 'public' & NamespaceId; readonly model: 'Floor' };
    readonly flat: { readonly namespace: 'public' & NamespaceId; readonly model: 'Flat' };
    readonly followUp: { readonly namespace: 'public' & NamespaceId; readonly model: 'FollowUp' };
  };
  readonly domain: {
    readonly namespaces: {
      readonly public: {
        readonly models: {
          readonly Area: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly name: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
            };
            readonly relations: {
              readonly buyer: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Buyer';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['areaId'];
                };
              };
              readonly colony: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Colony';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['areaId'];
                };
              };
              readonly seller: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Seller';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['areaId'];
                };
              };
            };
            readonly storage: {
              readonly table: 'area';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly name: { readonly column: 'name' };
              };
            };
          };
          readonly Buyer: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly clientId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly areaId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly length: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly width: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly budget: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly status: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly remarks: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
            };
            readonly relations: {
              readonly area: {
                readonly to: { readonly namespace: 'public' & NamespaceId; readonly model: 'Area' };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['areaId'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly client: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Client';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['clientId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'buyer';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly clientId: { readonly column: 'clientId' };
                readonly areaId: { readonly column: 'areaId' };
                readonly length: { readonly column: 'length' };
                readonly width: { readonly column: 'width' };
                readonly budget: { readonly column: 'budget' };
                readonly status: { readonly column: 'status' };
                readonly remarks: { readonly column: 'remarks' };
              };
            };
          };
          readonly Client: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly name: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly address: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly mobileNumber: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly remarks: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
            };
            readonly relations: {
              readonly buyer: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Buyer';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['clientId'];
                };
              };
              readonly followUp: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'FollowUp';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['clientId'];
                };
              };
              readonly marketing: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Marketing';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['clientId'];
                };
              };
              readonly seller: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Seller';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['clientId'];
                };
              };
            };
            readonly storage: {
              readonly table: 'client';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly name: { readonly column: 'name' };
                readonly address: { readonly column: 'address' };
                readonly mobileNumber: { readonly column: 'mobileNumber' };
                readonly remarks: { readonly column: 'remarks' };
              };
            };
          };
          readonly Colony: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly name: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly areaId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
            };
            readonly relations: {
              readonly area: {
                readonly to: { readonly namespace: 'public' & NamespaceId; readonly model: 'Area' };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['areaId'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly marketing: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Marketing';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['colonyId'];
                };
              };
              readonly wing: {
                readonly to: { readonly namespace: 'public' & NamespaceId; readonly model: 'Wing' };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['colonyId'];
                };
              };
            };
            readonly storage: {
              readonly table: 'colony';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly name: { readonly column: 'name' };
                readonly areaId: { readonly column: 'areaId' };
              };
            };
          };
          readonly Employee: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly name: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly phoneNumber: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
            };
            readonly relations: {
              readonly followUp: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'FollowUp';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['employeeId'];
                };
              };
              readonly marketing: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Marketing';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['employeeId'];
                };
              };
            };
            readonly storage: {
              readonly table: 'employee';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly name: { readonly column: 'name' };
                readonly phoneNumber: { readonly column: 'phoneNumber' };
              };
            };
          };
          readonly Flat: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly floorId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly type: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly flatNumber: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly status: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
            };
            readonly relations: {
              readonly floor: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Floor';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['floorId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'flat';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly floorId: { readonly column: 'floorId' };
                readonly type: { readonly column: 'type' };
                readonly flatNumber: { readonly column: 'flatNumber' };
                readonly status: { readonly column: 'status' };
              };
            };
          };
          readonly Floor: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly wingId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly numberOfFlats: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
            };
            readonly relations: {
              readonly flat: {
                readonly to: { readonly namespace: 'public' & NamespaceId; readonly model: 'Flat' };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['floorId'];
                };
              };
              readonly wing: {
                readonly to: { readonly namespace: 'public' & NamespaceId; readonly model: 'Wing' };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['wingId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'floor';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly wingId: { readonly column: 'wingId' };
                readonly numberOfFlats: { readonly column: 'numberOfFlats' };
              };
            };
          };
          readonly FollowUp: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly clientId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly employeeId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly dateTime: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
              readonly notes: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly status: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly purpose: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
            };
            readonly relations: {
              readonly client: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Client';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['clientId'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly employee: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Employee';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['employeeId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'followUp';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly clientId: { readonly column: 'clientId' };
                readonly employeeId: { readonly column: 'employeeId' };
                readonly dateTime: { readonly column: 'dateTime' };
                readonly notes: { readonly column: 'notes' };
                readonly status: { readonly column: 'status' };
                readonly purpose: { readonly column: 'purpose' };
              };
            };
          };
          readonly Marketing: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly clientId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly employeeId: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly colonyId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly remarks: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly status: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly priority: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
            };
            readonly relations: {
              readonly client: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Client';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['clientId'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly colony: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Colony';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['colonyId'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly employee: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Employee';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['employeeId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'marketing';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly clientId: { readonly column: 'clientId' };
                readonly employeeId: { readonly column: 'employeeId' };
                readonly colonyId: { readonly column: 'colonyId' };
                readonly remarks: { readonly column: 'remarks' };
                readonly status: { readonly column: 'status' };
                readonly priority: { readonly column: 'priority' };
              };
            };
          };
          readonly Seller: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly clientId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly areaId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly length: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly width: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly demand: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly status: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly remarks: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
            };
            readonly relations: {
              readonly area: {
                readonly to: { readonly namespace: 'public' & NamespaceId; readonly model: 'Area' };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['areaId'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly client: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Client';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['clientId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'seller';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly clientId: { readonly column: 'clientId' };
                readonly areaId: { readonly column: 'areaId' };
                readonly length: { readonly column: 'length' };
                readonly width: { readonly column: 'width' };
                readonly demand: { readonly column: 'demand' };
                readonly status: { readonly column: 'status' };
                readonly remarks: { readonly column: 'remarks' };
              };
            };
          };
          readonly Wing: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly colonyId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly name: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly numberOfFloors: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
            };
            readonly relations: {
              readonly colony: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Colony';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['colonyId'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly floor: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Floor';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['wingId'];
                };
              };
            };
            readonly storage: {
              readonly table: 'wing';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly colonyId: { readonly column: 'colonyId' };
                readonly name: { readonly column: 'name' };
                readonly numberOfFloors: { readonly column: 'numberOfFloors' };
              };
            };
          };
        };
        readonly enum: {
          readonly SellerStatus: {
            readonly codecId: 'pg/text@1';
            readonly members: readonly [
              { readonly name: 'UNSOLD'; readonly value: 'UNSOLD' },
              { readonly name: 'SOLD'; readonly value: 'SOLD' },
            ];
          };
          readonly BuyerStatus: {
            readonly codecId: 'pg/text@1';
            readonly members: readonly [
              { readonly name: 'NOTPURCHASED'; readonly value: 'NOTPURCHASED' },
              { readonly name: 'PURCHASED'; readonly value: 'PURCHASED' },
              { readonly name: 'CANCELLED'; readonly value: 'CANCELLED' },
            ];
          };
          readonly MarketingStatus: {
            readonly codecId: 'pg/text@1';
            readonly members: readonly [
              { readonly name: 'NONE'; readonly value: 'NONE' },
              { readonly name: 'CALLED_NOT_VISITED'; readonly value: 'CALLED_NOT_VISITED' },
              { readonly name: 'VISITED'; readonly value: 'VISITED' },
              { readonly name: 'NOT_INTERESTED'; readonly value: 'NOT_INTERESTED' },
            ];
          };
          readonly Priority: {
            readonly codecId: 'pg/text@1';
            readonly members: readonly [
              { readonly name: 'ONE_STAR'; readonly value: 'ONE_STAR' },
              { readonly name: 'TWO_STAR'; readonly value: 'TWO_STAR' },
              { readonly name: 'THREE_STAR'; readonly value: 'THREE_STAR' },
              { readonly name: 'FOUR_STAR'; readonly value: 'FOUR_STAR' },
              { readonly name: 'FIVE_STAR'; readonly value: 'FIVE_STAR' },
            ];
          };
          readonly FlatStatus: {
            readonly codecId: 'pg/text@1';
            readonly members: readonly [
              { readonly name: 'AVAILABLE'; readonly value: 'AVAILABLE' },
              { readonly name: 'SOLD'; readonly value: 'SOLD' },
            ];
          };
          readonly FollowUpStatus: {
            readonly codecId: 'pg/text@1';
            readonly members: readonly [
              { readonly name: 'PENDING'; readonly value: 'PENDING' },
              { readonly name: 'DONE'; readonly value: 'DONE' },
              { readonly name: 'POSTPONED'; readonly value: 'POSTPONED' },
              { readonly name: 'CANCELLED'; readonly value: 'CANCELLED' },
            ];
          };
          readonly FollowUpPurpose: {
            readonly codecId: 'pg/text@1';
            readonly members: readonly [
              { readonly name: 'GENERAL'; readonly value: 'GENERAL' },
              { readonly name: 'MARKETING'; readonly value: 'MARKETING' },
              { readonly name: 'BUYER'; readonly value: 'BUYER' },
              { readonly name: 'SELLER'; readonly value: 'SELLER' },
            ];
          };
        };
      };
    };
  };
  readonly capabilities: {
    readonly postgres: {
      readonly distinctOn: true;
      readonly jsonAgg: true;
      readonly lateral: true;
      readonly limit: true;
      readonly orderBy: true;
      readonly returning: true;
    };
    readonly sql: {
      readonly checkConstraint: true;
      readonly defaultInInsert: true;
      readonly enums: true;
      readonly lateral: true;
      readonly returning: true;
      readonly scalarList: true;
    };
  };
  readonly extensions: {};
  readonly meta: {};

  readonly profileHash: ProfileHash;
};

export type Contract = ContractWithTypeMaps<ContractBase, TypeMaps>;

export type Namespaces = Contract['storage']['namespaces'];
